var languageStorage = {
    "english": {
        "catLink": "cat",
        "dogLink": "dog",
        "rabbitLink": "rabbit",
        "mainHeading": "pets - medicine for the soul",
        "chooseHeading": "how to choose a pet",
        "chooseParag": "Regardless of all the complications that pets bring, the amount of love and happiness that animals bring to a home is immeasurable and worth every effort.",
        "bpHeading": "The best pets - cats and dogs",
        "bpParag": "The best pets are cats and dogs. At least that's what the number of families who narrowed their selection down to these two pets says. The choice can be difficult, because many factors separate them into two completely different categories.",
        "bhHeading": "but how to choose?",
        "bhParag": "Dogs are the ones that require much more time, attention and money. They are generally considered to be much more social than cats. On the other hand, cats are quite independent, they are much easier to care for, they are quite simple and take up a smaller part of the household budget.",
        "tcHeading": "you need to think carefully",
        "tcParag": "A dog is a very intelligent animal with which you will not have many problems. You can teach him some neat tricks. The independence of a cat as a pet can also be an advantage, because you won't have to worry when you leave the apartment for work and obligations.",
        "ayHeading": "think about yourself",
        "ayParag": "Cats are really good pets that you can cuddle a lot with, and if you don't have plenty of time it can be a good choice. On the other hand, if you have more time to devote to a pet, consider a dog because you can take it for long walks, runs and even bike rides.",
        "footer": "Designed and coded by",
        "footerLink": "Miroslav Jovic"
    },
    "serbian": {
        "catLink": "мачка",
        "dogLink": "пас",
        "rabbitLink": "зека",
        "mainHeading": "кућни љубимци - лек за душу",
        "chooseHeading": "како одабрати кућног љубимца",
        "chooseParag": "Без обзира на све компликације које доносе кућни љубимци, количина љубави и среће коју животиње доносе у дом је немерљива и вредна сваког труда.",
        "bpHeading": "Најбољи кућни љубимци - мачке и пси",
        "bpParag": "Најбољи кућни љубимци су мачке и пси. Бар тако каже велики број породица које су свој избор сузиле на ова два љубимца. Избор може бити тежак, јер их много фактора раздваја у две потпуно различите категорије.",
        "bhHeading": "али како изабрати?",
        "bhParag": "Пси су ти који захтевају много више времена, пажње и новца. Генерално се сматра да су много друштвенији од мачака. С друге стране, мачке су прилично независне, много лакше се брине о њима, прилично су једноставне и захтевају мањи део кућног буџета.",
        "tcHeading": "треба добро размислити",
        "tcParag": "Пас је веома интелигентна животиња са којом нећете имати много проблема. Можете га научити неким згодним триковима. Независност мачке као кућног љубимца такође може бити предност, јер нећете морати да бринете када изађете из стана због посла и обавеза.",
        "ayHeading": "размислите о себи",
        "ayParag": "Мачке су заиста добри кућни љубимци са којима се можете много мазити, а ако немате довољно времена то може бити добар избор. С друге стране, ако имате више времена да се посветите кућном љубимцу, размислите о псу јер га можете водити у дуге шетње, трчање, па чак и вожњу бициклом.",
        "footer": "Дизајнирао и кодирао",
        "footerLink": "Мирослав Јовић"
    },
    "spanish": {
        "catLink": "gato",
        "dogLink": "perro",
        "rabbitLink": "conejito",
        "mainHeading": "mascotas - medicina para el alma",
        "chooseHeading": "como elegir una mascota",
        "chooseParag": "Independientemente de todas las complicaciones que traen las mascotas, la cantidad de amor y felicidad que los animales traen a un hogar es inconmensurable y vale la pena cada esfuerzo.",
        "bpHeading": "Las mejores mascotas - perros y gatos",
        "bpParag": "Las mejores mascotas son los gatos y los perros. Al menos eso es lo que dice el número de familias que redujeron su selección a estas dos categorías. La elección puede ser difícil, porque muchos factores los separan en dos categorías completamente diferentes.",
        "bhHeading": "pero como elegir?",
        "bhParag": "Los perros son los que requieren mucho más tiempo, atención y dinero. Generalmente se les considera mucho más sociales que los gatos. Por otro lado, los gatos son bastante independientes, son mucho más fáciles de cuidar, son bastante sencillos y ocupan una parte menor del presupuesto del hogar.",
        "tcHeading": "tienes que pensar con cuidado",
        "tcParag": "Un perro es un animal muy inteligente con el que no tendrás muchos problemas. Puedes enseñarle algunos buenos trucos. La independencia de un gato como mascota también puede ser una ventaja, porque no tendrás que preocuparte cuando salgas del apartamento por trabajo y obligaciones.",
        "ayHeading": "piensa en ti mismo",
        "ayParag": "Los gatos son muy buenas mascotas a las que puedes abrazar mucho y, si no tienes mucho tiempo, pueden ser una buena opción. Por otro lado, si tienes más tiempo para dedicarle a una mascota, considera un perro porque puedes llevarlo a dar largos paseos, carreras e incluso paseos en bicicleta.",
        "footer": "Diseñado y codificado por",
        "footerLink": "Miroslav Jovic"
    },
    "russian": {
        "catLink": "кошка",
        "dogLink": "собака",
        "rabbitLink": "кролик",
        "mainHeading": "домашние животные - лекарство для души",
        "chooseHeading": "как выбрать домашнее животное",
        "chooseParag": "Несмотря на все сложности, которые приносят домашние животные, количество любви и счастья, которые животные приносят в дом, неизмеримо и стоит любых усилий.",
        "bpHeading": "Лучшие домашние животные - кошки и собаки",
        "bpParag": "Лучшие домашние животные – это кошки и собаки. По крайней мере, так говорит количество семей, сузивших свой выбор до этих двух категорий. Выбор может быть сложным, потому что многие факторы разделяют их на две совершенно разные категории.",
        "bhHeading": "но как выбрать?",
        "bhParag": "Собаки требуют гораздо больше времени, внимания и денег. Обычно считается, что они гораздо более общительны, чем кошки. С другой стороны, кошки достаточно самостоятельны, за ними гораздо легче ухаживать, они довольно просты и занимают меньшую часть домашнего бюджета.",
        "tcHeading": "вам нужно хорошо подумать",
        "tcParag": "Собака — очень умное животное, с которым у вас не будет много проблем. Вы можете научить его некоторым хитрым трюкам. Независимость кошки как домашнего питомца также может быть преимуществом, ведь вам не придется беспокоиться, когда вы покидаете квартиру по работе и обязательствам.",
        "ayHeading": "подумай о себе",
        "ayParag": "Кошки — действительно хорошие домашние животные, с которыми можно много обниматься, и если у вас мало времени, это может быть хорошим выбором. С другой стороны, если у вас есть больше времени, чтобы посвятить домашнему животному, подумайте о собаке, потому что вы можете брать ее с собой на длительные прогулки, пробежки и даже поездки на велосипеде.",
        "footer": "Разработано и закодировано",
        "footerLink": "Мирослав Йович"
    },
    "french": {
        "catLink": "chat",
        "dogLink": "chien",
        "rabbitLink": "lapin",
        "mainHeading": "animaux de compagnie - médecine pour l'âme",
        "chooseHeading": "comment choisir un animal de compagnie",
        "chooseParag": "Indépendamment de toutes les complications que les animaux de compagnie apportent, la quantité d'amour et de bonheur que les animaux apportent à une maison est incommensurable et vaut tous les efforts.",
        "bpHeading": "Les meilleurs animaux de compagnie - chats et chiens",
        "bpParag": "Les meilleurs animaux de compagnie sont les chats et les chiens. C'est du moins ce que dit le nombre de familles qui ont réduit leur sélection à ces deux catégories. Le choix peut être difficile, car de nombreux facteurs les séparent en deux catégories complètement différentes.",
        "bhHeading": "mais comment choisir?",
        "bhParag": "Los perros son los que requieren mucho más tiempo, atención y dinero. Generalmente se les considera mucho más sociales que los gatos. Por otro lado, los gatos son bastante independientes, son mucho más fáciles de cuidar, son bastante sencillos y ocupan una parte menor del presupuesto del hogar.",
        "tcHeading": "il faut bien réfléchir",
        "tcParag": "Un chien est un animal très intelligent avec lequel vous n'aurez pas beaucoup de problèmes. Vous pouvez lui apprendre quelques trucs sympas. L'indépendance d'un chat en tant qu'animal de compagnie peut également être un avantage, car vous n'aurez pas à vous inquiéter lorsque vous quitterez l'appartement pour le travail et les obligations.",
        "ayHeading": "pense à toi",
        "ayParag": "Les chats sont de très bons animaux de compagnie avec lesquels vous pouvez beaucoup câliner, et si vous n'avez pas beaucoup de temps, cela peut être un bon choix. En revanche, si vous avez plus de temps à consacrer à un animal de compagnie, pensez à un chien car vous pourrez l'emmener pour de longues promenades, des courses et même des balades à vélo.",
        "footer": "Conçu et codé par",
        "footerLink": "Miroslav Jovic"
    },
    "german": {
        "catLink": "katze",
        "dogLink": "hund",
        "rabbitLink": "hase",
        "mainHeading": "Haustiere - Medizin für die Seele",
        "chooseHeading": "wie man ein Haustier auswählt",
        "chooseParag": "Ungeachtet aller komplikationen, die haustiere mit sich bringen, ist die menge an liebe und glück, die tiere in ein zuhause bringen, unermesslich und jede anstrengung wert.",
        "bpHeading": "Die besten haustiere - katzen und hunde",
        "bpParag": "Die besten haustiere sind katzen und hunde. Das sagt zumindest die zahl der familien, die ihre auswahl auf diese beiden haustiere eingegrenzt haben. Die wahl kann schwierig sein, da viele faktoren sie in zwei völlig unterschiedliche kategorien einteilen.",
        "bhHeading": "aber wie wählen?",
        "bhParag": "Hunde sind diejenigen, die viel mehr zeit, aufmerksamkeit und geld benötigen. Sie gelten allgemein als viel sozialer als katzen. Andererseits sind katzen ziemlich unabhängig, sie sind viel pflegeleichter, sie sind ziemlich einfach und nehmen einen kleineren teil des haushaltsbudgets in anspruch.",
        "tcHeading": "Sie müssen sorgfältig überlegen",
        "tcParag": "Ein hund ist ein sehr intelligentes tier, mit dem sie nicht viele probleme haben werden. Du kannst ihm ein paar nette tricks beibringen. Die unabhängigkeit einer Katze als haustier kann auch von vorteil sein, denn sie müssen sich keine sorgen machen, wenn sie die wohnung für arbeit und verpflichtungen verlassen.",
        "ayHeading": "denk an dich",
        "ayParag": "Katzen sind wirklich gute haustiere, mit denen man viel kuscheln kann, und wenn man nicht viel zeit hat, kann es eine gute Wahl sein. Wenn sie andererseits mehr zeit für ein haustier haben, sollten sie einen hund in betracht ziehen, da sie mit ihm lange spaziergänge, läufe und sogar radtouren machen können.",
        "footer": "Entworfen und codiert von",
        "footerLink": "Miroslav Jovic"
    }
}